def draw_library():
    print("<      / \          / \>")
    print("<     /   \        /   \>")
    print("<    /     \      /     \>")
    print("<   /       \    /       \>")
    print("<  /         \  /         \>")
    print("< /           \/           \>")
    print("<|             |            |>")
    print("<|             |            |>")
    print("<|   -----     |    -----   |>")
    print("<|   |   |     |    |   |   |>")
    print("<|   |   |     |    |   |   |>")
    print("<|   -----     |    -----   |>")
    print("<|             |            |>")
    print("<|             |            |>")
    print("<|             |            |>")
    print("<|             |            |>")
    print("<|             |            |>")
    print(" ---------------------------- ")
    return

draw_library()